# Generated by Django 2.1.2 on 2018-10-25 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='component',
            fields=[
                ('uniq_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='component_detail',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('type_of_comp', models.CharField(max_length=200)),
                ('level', models.BooleanField(default=False)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='due',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.component_detail')),
            ],
        ),
        migrations.CreateModel(
            name='issue_detail',
            fields=[
                ('packet_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('no_of_days', models.IntegerField()),
                ('fine_p_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('packet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.issue_detail')),
                ('uniq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.component')),
            ],
        ),
        migrations.CreateModel(
            name='pre_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('issued_packet_id', models.CharField(max_length=20)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.component_detail')),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_comp', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('approval_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.FloatField()),
                ('no_of_reviews', models.IntegerField()),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.component_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.CharField(default='s20160010', max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='first_name', max_length=50)),
                ('middle_name', models.CharField(blank=True, default='middle_name', max_length=50)),
                ('last_name', models.CharField(default='last_name', max_length=50)),
                ('regis_year', models.IntegerField(default='2016')),
                ('gender', models.CharField(default='M', max_length=1)),
                ('curr_year', models.IntegerField(default=3)),
                ('regis_deg', models.CharField(default='B.Tech', max_length=20)),
                ('regis_deg_dur', models.IntegerField(default=3)),
                ('curr_sem', models.IntegerField(default=5)),
                ('blood_grp', models.CharField(default='B-', max_length=20)),
                ('email', models.EmailField(default='example@iiits.in', max_length=254)),
                ('phone', models.CharField(default='123456789', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.Student'),
        ),
        migrations.AddField(
            model_name='pre_order',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.Student'),
        ),
        migrations.AddField(
            model_name='issue_detail',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.Student'),
        ),
        migrations.AddField(
            model_name='due',
            name='packet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.packet'),
        ),
        migrations.AddField(
            model_name='due',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.Student'),
        ),
        migrations.AddField(
            model_name='component',
            name='comp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.component_detail'),
        ),
        migrations.AddField(
            model_name='cart',
            name='comp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.component_detail'),
        ),
        migrations.AddField(
            model_name='cart',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclabmanagement.Student'),
        ),
    ]
