# Generated by Django 2.1.2 on 2018-11-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclabmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requestcomp',
        ),
    ]
