# Generated by Django 2.1.2 on 2018-11-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclabmanagement', '0002_auto_20181109_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcomp',
            name='on_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
